name: Backup Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the main branch code
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main # Ensures we're checking out the main branch

      # Step 2: Configure Git credentials
      - name: Configure Git Credentials
        run: |
          git config --global user.email "marcusaheins@gmail.com"
          git config --global user.name "MarcusProgramming"

      # Step 3: Create and switch to the backup branch (if it doesn't exist)
      - name: Checkout or create backup branch
        run: |
          git checkout backup || git checkout -b backup

      # Step 4: Sync backup (commit and push changes)
      - name: Sync backup
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated backup: $(date)"
          git push origin backup # Push changes to the backup branch
